### ISSUE TITLE
Support for `nvim_buf_set_keymap`

### ISSUE THREAD

**Issue by tom-anders** [LionC/nest.nvim#1]
As the title says, would be cool if this Plugin also supported buffer local key maps

**Comment by LionC** [comment]
Makes, sense - I will look into it. Adding a `buffer = true` cascading config field might be enough to solve that.

**Comment by LionC** [comment]
This has been implemented and tested in the linked PR. It will be released in v1.1.

**Comment by tom-anders** [comment]
Cool stuff!

**Comment by tom-anders** [comment]
Ah I didn't see your edit - but looks like it now supports both the current buffer and other buffers, right?

**Comment by LionC** [comment]
> Ah I didn't see your edit - but looks like it now supports both the current buffer and other buffers, right?

Yes, `buffer = false` (default) is global, `buffer = true` is the current buffer and `buffer = <somenumber>` is buffer <somenumber> :-)

I added it to the docs (and the introductory example) as well, you can poke around the v1.1 release branch if you want to take a look.
