### ISSUE TITLE
Potential issues before Release v1.1

### ISSUE THREAD

**Issue by stasjok** [LionC/nest.nvim#12]
Thank you for quickly adding missing features, but:
1. The following mapping wouldn't work for `expr = true`:
https://github.com/LionC/nest.nvim/blob/2ed1bfd4a2884c43a4a1ee59611307d03087a62b/lua/nest.lua#L98
You need to use something like luaeval without `<Cmd>...<CR>` if `expr = true`.
2. This loop wouldn't work for empty mode:
https://github.com/LionC/nest.nvim/blob/2ed1bfd4a2884c43a4a1ee59611307d03087a62b/lua/nest.lua#L101
I think it's useful to support `""` mode (`:map`)

**Comment by stasjok** [comment]
3. Also, I don't know if it's a big deal, but if someone likes to reload config by sourcing it multiple times, functions would be added to `require("nest").functions` every time. Maybe add them to the table with some unique key like `mode..lhs`? But in this case indexing by hash is slower than indexing by number (probably negligibly).

**Comment by LionC** [comment]
Thanks!

> 1. The following mapping wouldn't work for `expr = true`:
>    https://github.com/LionC/nest.nvim/blob/2ed1bfd4a2884c43a4a1ee59611307d03087a62b/lua/nest.lua#L98
>    
>    You need to use something like luaeval without `<Cmd>...<CR>` if `expr = true`.

I will take a loot at the `expr` thing - although it is probably not a big deal, as the arbitrary lua function can execute a dynamically built command with a simple `vim.cmd(command)` anyways. But it would be consistent to fix it either way

> 2. This loop wouldn't work for empty mode:
>     https://github.com/LionC/nest.nvim/blob/2ed1bfd4a2884c43a4a1ee59611307d03087a62b/lua/nest.lua#L101
>     
>     I think it's useful to support `""` mode (`:map`)

I am not even sure if empty mode is currently supported^^ If it is, it is by accident. I have to think about if this is something I want to do this way - `mode = ''` is not very expressive, is definitely does not express the fact that it binds a lot of modes...



For

> 3. Also, I don't know if it's a big deal, but if someone likes to reload config by sourcing it multiple times, functions would be added to `require("nest").functions` every time. Maybe add them to the table with some unique key like `mode..lhs`? But in this case indexing by hash is slower than indexing by number (probably negligibly).

I will look into this, although I would not want to make performance tradeoffs to support cleaner reloading.

**Comment by LionC** [comment]
I fixed the first two points and decided not to make config live reloading a priority now - there seems to be no canonical way to do this and most people just restart or unload the module anyways.

The other two things work fine - especially the `expr` one took a moment though, learned a lot about vim lua internals :-)

Thank you for the input!
