### ISSUE TITLE
Trouble with expr(s)

### ISSUE THREAD

**Issue by Luc-Saccoccio** [LionC/nest.nvim#20]
I want to keybind Tab and Shift Tab, and I was using this :
```lua
local function map(mode, lhs, rhs, opts)
    local options = {noremap = true, silent = true}
    if opts then
        options = vim.tbl_extend("force", options, opts)
    end
    vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

map('i', '<Tab>', 'pumvisible() ? "\\<C-n>" : "\\<Tab>"', {noremap = true, expr = true})
map('i', '<S-Tab>', 'pumvisible() ? "\\<C-p>" : "\\<S-Tab>"', {noremap = true, expr = true})
```

With `nest.nvim`, I tough I could do it that way :
```lua
local nest = require('nest')
nest.applyKeymaps(
	{ mode='i', options = { expr = true, noremap = true, silent = false }, {
		{ "<Tab>", 'pumvisible ? "\\<C-n>" : "\\<Tab>"' },
		{ "<S-Tab>", 'pumvisible ? "\\<C-p>" : "\\<S-Tab>"' },
	}})
```
But when using Tab and Shit Tab the same way as before, I get
```
E121: Undefined variable pumvisible
E15: Invalid Expression : pumvisible ? "\N^" : "\I^"
```

I have trouble understanding why it doesn't work :/

**Comment by LionC** [comment]
Will take a look tonight!

**Comment by Luc-Saccoccio** [comment]
Thanks a lot !

To clarify, I use these bindings with [completion-nvim](https://github.com/nvim-lua/completion-nvim), to replace the <C-n>/<C-p> keybinds

**Comment by LionC** [comment]
> ```lua
> map('i', '<Tab>', 'pumvisible() ? "\\<C-n>" : "\\<Tab>"', {noremap = true, expr = true})
> map('i', '<S-Tab>', 'pumvisible() ? "\\<C-p>" : "\\<S-Tab>"', {noremap = true, expr = true})
> ```
> 
> ```lua
> {
> 		{ "<Tab>", 'pumvisible ? "\\<C-n>" : "\\<Tab>"' },
> 		{ "<S-Tab>", 'pumvisible ? "\\<C-p>" : "\\<S-Tab>"' },
> }
> ```

Is it just a typo that the parentheses after `pumvisible()` are missing in the second example `pumvisible`?

**Comment by Luc-Saccoccio** [comment]
Oh, I feel terribly dumb now ._.

I'm really sorry to have bothered you

**Comment by LionC** [comment]
Don't worry, that happens to all of us sometimes :-) I am glad that it works for you now!
