### ISSUE TITLE
For new users, to make nest.nvim awesome!

### ISSUE THREAD

**Issue by vzytoi** [LionC/nest.nvim#32]
I've been using nest.nvim for a bit now so I just wanted to share with you guys how this plugin can be really really powerfull!
So basically you can make requires inside `nest.applyKeymaps { }`. This way, you can put your mappings all over your configuration and have it really more organized. This is really nice for telescope configuration for instance. If you want me to explaine a little bit more or show other example just ask me (:

_In mappings.lua :_
```lua
local nest  = require("nest")

function QueryMapping()

    local setups = {
        "telescope",
        "coc",
        "term",
        "runcode",
        "resize"
    }

    local map = {}

    for _, s in ipairs(setups) do
        table.insert(map, require("plugins." .. s).setup()[1])
    end

    return map

end

nest.applyKeymaps {
    QueryMapping()
}

```
_In resize.lua (for example)_
```lua
local M = {}

function M.setup()

    local map = {
        { '<a-', {}}
    }

    local k = {
        'h', 'l', 'k', 'j'
    }

    for i, _ in ipairs(k) do
        table.insert(map[1][2],
            {k[i] .. '>',
            function()
                M.ResizeWindow(k[i])
            end
        })
    end

    return map

end

function M.ResizeWindow(k)
    local wcount = vim.fn.winnr("$")
    local wcurr = vim.fn.winnr()

    local sl = {}
    sl.h = "-"
    sl.l = "+"

    function Reverse(s)
        return (s == "-" and "+" or "-")
    end

    function Exec(d, s)
        local c = d .. "res " .. s .. "5"
        vim.api.nvim_command(c)
    end

    local s

    if sl[k] ~= nil then
        if wcurr == wcount then
            s = Reverse(sl[k])
        else
            s = sl[k]
        end
        Exec("vert ", s)
    else
        sl.k = sl.l
        sl.j = sl.h
        Exec("", sl[k])
    end
end

return M

```

**Comment by LionC** [comment]
Very abstract use of the plugin, glad to see that it is flexible enough for that case as well :-) I opted to have all my keybinds in one place, as it felt more important to have a central overview for them than to have one place to remove a plugin. Either way definitely has tradeoffs and the central overview thing will be easier once the inspection feature lands.

I tried to convey your point in the docs with that quote btw:

> Because nest-keymapConfigs are just simple Lua values, they can be defined in their own files, passed around, plugged into different prefixes or options etc.

but maybe that was too abstract^^
