### ISSUE TITLE
How do I add a mapping that contains a backslash?

### ISSUE THREAD

**Issue by benwoodward** [LionC/nest.nvim#33]
I think the backslash is the issue here, but not sure. 

I want to convert this mapping to nest.nvim syntax:

```vimscript
" Copy visual selection to system clipboard
noremap <silent> <leader>y :<CR>:let @a=@" \| execute "normal! vgvy" \| let res=system("pbcopy", @") \| let @"=@a<CR>
```

I've tried: 

`{ 'y', ':<CR>:let @a=@" | execute "normal! vgvy" | let res=system("pbcopy", @") | let @"=@a<CR>' },`
`{ 'y', ':<CR>:let @a=@" \| execute "normal! vgvy" \| let res=system("pbcopy", @") \| let @"=@a<CR>' },`
`{ 'y', ':<CR>:let @a=@" \\| execute "normal! vgvy" \\| let res=system("pbcopy", @") \\| let @"=@a<CR>' },`

But none work.

The second example causes the following error on load:

```
E5113: Error while calling lua chunk: vim.lua:64: /Users/ben/.config/nvim/lua/core/keymaps.lua:94: invalid escape sequence near '':<CR>:let @a=@" '
```

The first and last don't cause any errors.

This used to work before I switched to lua.

**Comment by NTBBloodbath** [comment]
Hi, have you tried using raw Lua strings? In that way you'll not need to escape stuff (not sure if this would work tho).

If you don't know how to use them, they use `[[` and `]]` as delimiters instead of single/double quotes. Hope it works :)

**Comment by benwoodward** [comment]
Okay, what worked was removing the backslashes, and adding `mode = 'v'`

`{ 'y', ':<CR>:let @a=@" | execute "normal! vgvy" | let res=system("pbcopy", @") | let @"=@a<CR>]]', mode = 'v'},`

**Comment by LionC** [comment]
I think you do not need to escape `|` at all in Lua, no matter what kind of string you are using, which was the problem here.
