### ISSUE TITLE
Ability to map same output for many inputs

### ISSUE THREAD

**Issue by veged** [LionC/nest.nvim#35]
Is there any way to bind _**same**_ output for many inputs? For example, if I would like to have `<Leader>q` and `<Leader>Q` both mapped to `<Cmd>q<CR>`, it could be like this:
```lua
require('nest').applyKeymaps({
  { { '<Leader>q', '<Leader>Q' }, '<Cmd>q<CR>' }
})
```
or using nesting:
```lua
require('nest').applyKeymaps({
  { '<Leader>', {
    { { 'q', 'Q' }, '<Cmd>q<CR>' }
  }}
})
```

**Comment by LionC** [comment]
nest Keymaps are normal Lua tables, so you could put that value in a variable if you want to DRY it up, e.g.:

```lua
local cmdQ = '<Cmd>q<CR>'

require 'nest'.applyKeymaps {
    { '<Leader>', {
        { 'q', cmdQ },
        { 'q', cmdQ },
    }},
}
```

Having an own syntax for multiple binds would work I guess, but I am not too sure if the semantics are obvious enough (especially if you have more nested binds, does it multiplex?) and if that is actually significantly better in any way than the example above.

**Comment by veged** [comment]
> nest Keymaps are normal Lua tables, so you could put that value in a variable if you want to DRY it up, e.g.:
> 
> 
> 
> ```lua
> 
> local cmdQ = '<Cmd>q<CR>'
> 
> 
> 
> require 'nest'.applyKeymaps {
> 
>     { '<Leader>', {
> 
>         { 'q', cmdQ },
> 
>         { 'q', cmdQ },
> 
>     }},
> 
> }
> 
> ```
> 
> 
> 
> Having an own syntax for multiple binds would work I guess, but I am not too sure if the semantics are obvious enough (especially if you have more nested binds, does it multiplex?) and if that is actually significantly better in any way than the example above.

just imagine, how many variables we need in case of double binds for at least every second binding... concoct names for all of them... and also lexical order of such declarations (with variables) would be "unnatural"

the suggested semantic is straightforward — all arrays means multiplex as if there will be few separate declarations with same value

I could try to provide PR, if you will be generously open for it...
