### ISSUE TITLE
Allow arbitrary `lua` functions for right side keymap values

### ISSUE THREAD

**Issue by LionC** [LionC/nest.nvim#5]

**Comment by Corey-Keller** [comment]
I saw on Reddit that you "just do not have a design that [you] like yet."
I was curious what, if any, designs you've considered and what it is that do/don't like about them?

I figure if it's still in the design phase it might be a good idea to involve the community in the discussion to help ensure it's done the best way right out of the gate.

**Comment by LionC** [comment]
By design I mostly meant how to implement it (sorry, I was unclear there). The API is straightforwRd I think - just pass a function instead of a key sequence as the second value in a keymap.

I have implemented a first version and included it in the docs. If you are interested to see it, just look into the Draft PR linked to this issue :-)

**Comment by LionC** [comment]
Implementation and documentation is done, this will be in v1.1
